language: android
sudo: required
jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_API=25
    - EMULATOR_API=25
    - ANDROID_BUILD_TOOLS=25.0.0
    - ADB_INSTALL_TIMEOUT=5 # minutes

branches:
  only:
  - espresso_tests_travis_ci

android:
  components:
  - tools
  - platform-tools
  - build-tools-$ANDROID_BUILD_TOOLS
  - android-$ANDROID_API
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository # for design library
  - addon-google_apis-google-19 # google play services
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL

#before_script:
#  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell input keyevent 82 &

#script:
#  - android list targets
#  - echo no | android create avd --force -n test -t android-23 --abi x86
#  - emulator -avd test -no-skin -no-audio -no-window &
#  - android-wait-for-emulator
#  - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
#  - ./gradlew installDebug

script:
  - android list targets
#  -"./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"

after_success:
  - bash echo "Yata!"